### Task Instructions for Students:
1. *Create a Task class* that will hold task attributes (title, description, status, due_date), and implement a __str__ method for displaying the task details.
2. *Create a TaskManager class* that will manage multiple tasks. This class will handle CRUD operations, such as creating, reading, updating, and deleting tasks.
3. *Handle edge cases* such as:
   - Trying to update or delete a non-existent task.
   - Attempting to read or print all tasks when no tasks have been created.
4. *Testing*: Test the system by adding several tasks, viewing them, updating their status, and deleting tasks.




In [ ]:
class Task:
    def __init__(self, title, description, status, due_date):
        self.title = title
        self.description = description
        self.status = status
        self.due_date = due_date

    def __str__(self):
        return f"ID: {self.id} | Title: {self.title} | Status: {self.status} | Due Date: {self.due_date}"

class TaskManager :
    def __init__(self):
        self.tasks = {} 
        self.next_id = 1  # To generate unique task IDs

    def create_task(self, title, description, status, due_date):
        task = Task(title, description, status, due_date) #store all task
        task.id = self.next_id #1
        self.tasks[self.next_id] = task #
        self.next_id += 1 #auto inc.
        return f"Task {task.id} created successfully!"
    def read_all_tasks(self):
        if not self.tasks:
            print("No tasks available.")
        for task in self.tasks.values():
            print(task)
    def read_task(self,task_id):
        task = self.tasks.get(task_id) # 2
        if task: # if 2
            print(task)
        else: 
            print(f"Task with ID {task_id} not found.")
    def update_task(self, task_id, title=None, description=None, status=None, due_date=None):
        task = self.tasks.get(task_id)
        if task: 
            if title:
                task.title = title
            if description:
                task.description = description
            if status:
                task.status = status
            if due_date:
                task.due_date = due_date
            print(f"Task {task_id} updated successfully!")
        else:
            print(f"Task with ID {task_id} not found.")
    def delete_task(self, task_id):
        if task_id in self.tasks:
            del self.tasks[task_id]
            print(f"Task {task_id} deleted successfully!")
        else:
            print(f"Task with ID {task_id} not found.")

manager = TaskManager()

print(manager.create_task("Python","Core python syllabus","Completed","12-08-2025"))
print(manager.create_task("Python","Html,CSS,JS","Pending","12-08-2025"))
print(manager.read_all_tasks())
print(manager.update_task(2,status="Completed",due_date = " "))
print(manager.read_task(2))
print(manager.read_all_tasks())
print(manager.delete_task(1))
print(manager.read_all_tasks())


In [29]:
class Task:
    def __init__(self, title, description, status, due_date):
        self.title = title
        self.description = description
        self.status = status
        self.due_date = due_date

    def __str__(self):
        return f"ID: {self.id} | Title: {self.title} | Status: {self.status} "

book1 = Task("Python","Basic Python","Pending","25-02-2026")
class TaskManager :
    def __init__(self):
        self.tasks = {} 
        self.next_id = 1  # To generate unique task IDs

    def create_task(self, title, description, status, due_date):
        task = Task(title, description, status, due_date) #store all task
        task.id = self.next_id #1
        self.tasks[self.next_id] = task #
        self.next_id += 1 #auto inc.
        return f"Task {task.id} created successfully!"
    def read_all_tasks(self):
        if not self.tasks:
            print("No tasks available.")
        for task in self.tasks.values():
            print(task)  
    def read_task(self,task_id):
        task = self.tasks.get(task_id) # 2
        if task: # if 2
            print(task)
        else: 
            print(f"Task with ID {task_id} not found.")     

    def update_task(self, task_id, title=None, description=None, status=None, due_date=None):
        task = self.tasks.get(task_id)
        if task: 
            if title:
                task.title = title
            if description:
                task.description = description
            if status:
                task.status = status
            if due_date:
                task.due_date = due_date
            print(f"Task {task_id} updated successfully!")
        else:
            print(f"Task {task_id} Not Found!")
    def delete_task(self, task_id):
        if task_id in self.tasks:
            del self.tasks[task_id]
            print(f"Task {task_id} deleted successfully!")
        else:
            print(f"Task with ID {task_id} not found.")        
            


Manager = TaskManager()
Manager.create_task("Python","Basic Python","Pending","25-02-2026")
Manager.create_task("UI","Frontend book","Ava","24-02-2026")
print(Manager.read_all_tasks())
Manager.delete_task(1)
print(Manager.read_all_tasks())

ID: 1 | Title: Python | Status: Pending 
ID: 2 | Title: UI | Status: Ava 
None
Task 1 deleted successfully!
ID: 2 | Title: UI | Status: Ava 
None


In [3]:
class Task:
    def __init__(self, title, description, status, due_date):
        self.title = title
        self.description = description
        self.status = status
        self.due_date = due_date

    def __str__(self):
        return f"Title: {self.title} | Status: {self.status} | Due Date: {self.due_date}"
obj1 = Task('abc','sjhdsjd','pending','23/03/2025')
obj1.__str__()

'Title: abc | Status: pending | Due Date: 23/03/2025'

In [34]:
#create task 
class Task:
    def __init__(self, title, description, status, due_date):
        self.title = title
        self.description = description
        self.status = status
        self.due_date = due_date

    def __str__(self):
        return f"ID: {self.id} | Title: {self.title} | Status: {self.status} | Due Date: {self.due_date}"

class TaskManager :
    def __init__(self):
        self.tasks = {}
        self.next_id = 1  # To generate unique task IDs

    def create_task(self, title, description, status, due_date):
        task = Task(title, description, status, due_date) #store all task
        task.id = self.next_id #1
        self.tasks[self.next_id] = task #
        self.next_id += 1 #auto inc.
        return f"Task {task.id} {task.title} {task.description} created successfully!"

    def read_all_tasks(self):
        if not self.tasks:
            print("No tasks available.")
        for task in self.tasks.values():
            print(task)
    def read_task(self,task_id):
        task = self.tasks.get(task_id) # 2
        if task: # if 2
            print(task)
        else: 
            print(f"Task with ID {task_id} not found.")      
    def update_task(self, task_id, title=None, description=None, status=None, due_date=None):
        task = self.tasks.get(task_id)
        if task: 
            if title:
                task.title = title
            if description:
                task.description = description
            if status:
                task.status = status
            if due_date:
                task.due_date = due_date
            print(f"Task {task_id} updated successfully!")
        else:
            print(f"Task with ID {task_id} not found.")        

    def delete_task(self, task_id):
        if task_id in self.tasks:
            del self.tasks[task_id]
            print(f"Task {task_id} deleted successfully!")
        else:
            print(f"Task with ID {task_id} not found.")

manager = TaskManager()
manager.create_task('python','basic of Python','active','2/11/2025')
manager.create_task('UI','Front End Tech...','pending','12/11/2025')
manager.create_task('python','basic of Python','active','2/11/2025')
manager.create_task('UI','Front End Tech...','pending','12/11/2025')
manager.create_task('python','basic of Python','active','2/11/2025')
manager.create_task('UI','Front End Tech...','pending','12/11/2025')
manager.create_task('python','basic of Python','active','2/11/2025')
manager.create_task('UI','Front End Tech...','pending','12/11/2025')
manager.read_all_tasks()
#manager.read_task(3)
#manager.update_task(3, title = 'Full-stack Python',status = 'pending')
#manager.read_task(3)
manager.delete_task(10)
manager.read_all_tasks()

ID: 1 | Title: python | Status: active | Due Date: 2/11/2025
ID: 2 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 3 | Title: python | Status: active | Due Date: 2/11/2025
ID: 4 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 5 | Title: python | Status: active | Due Date: 2/11/2025
ID: 6 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 7 | Title: python | Status: active | Due Date: 2/11/2025
ID: 8 | Title: UI | Status: pending | Due Date: 12/11/2025
Task with ID 10 not found.
ID: 1 | Title: python | Status: active | Due Date: 2/11/2025
ID: 2 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 3 | Title: python | Status: active | Due Date: 2/11/2025
ID: 4 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 5 | Title: python | Status: active | Due Date: 2/11/2025
ID: 6 | Title: UI | Status: pending | Due Date: 12/11/2025
ID: 7 | Title: python | Status: active | Due Date: 2/11/2025
ID: 8 | Title: UI | Status: pending | Due Date: 12/11/2025


In [36]:
import numpy as np

In [37]:
array  = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [38]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
set1 = (1,2,3,4,5,6)
array2 = np.array(set1)
array2

array([1, 2, 3, 4, 5, 6])

In [41]:
list1 = [[1,2,3,4],[5,6,7,8]]
print(list1)
print('..................................')
array3 = np.array(list1)
print(array3)

[[1, 2, 3, 4], [5, 6, 7, 8]]
..................................
[[1 2 3 4]
 [5 6 7 8]]


In [42]:
# Zero Array
array = np.array([[0,0,0],[0,0,0]])
array

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# pip install numpy 

In [44]:
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

In [46]:
zero_array = np.zeros((2,5),dtype = int)
zero_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])