In [2]:
import numpy as np


In [ ]:
pip install numpy 

numpy Array functions :
                      1.np.array()
                      2.np.len()
                      3.np.min()
                      4.np.max()
                      5.mean()
                      6.median()
                      7.zeros()
                      8.ones()
                      9.sum()
                      10.eye()
                      11.arange()
                      12.sort()
                      13.random.rand()
                      14.random.randn()
                      15.random.randint()  
                      16.squre()
                      17.sqrt()
                      18.std()
                      19.var()
                      20.reshape()


In [5]:
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
a2 = np.array(["Rahul","Rohan","Harsh"])
print(a2)

['Rahul' 'Rohan' 'Harsh']


In [18]:
list1 = [1,2,3,4,5]
a3 = np.array(list1)
print(a3)
print(type(list1))
print(type(a3))

[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [11]:
list2 = [1,2,3,[4,5],[6,7]]
print(list2)

[1, 2, 3, [4, 5], [6, 7]]


In [12]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [14]:
a11 = np.array([[1,2,3],[4,5,6]])
print(a11)

[[1 2 3]
 [4 5 6]]


In [20]:
array1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
array2 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(array2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [35]:
a11 = np.array([1,2,3,4,5,6,7])
print(a11)
print(len(a11))
print(min(a11))
print(max(a11))


[1 2 3 4 5 6 7]
7
1
7


In [36]:
print(a11)
print(sum(a11))
print(a11.mean())

[1 2 3 4 5 6 7]
28
4.0


In [39]:
m=np.median(a11)
print(m)

4.0


In [42]:
arr1 = np.array([1,2,3,4,5])
m = np.median(arr1)
print(m)
mean = np.mean(arr1)
print(mean)

3.0
3.0


In [44]:
arr2 = np.zeros([2,3])
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr2 = np.zeros([2,3],dtype=int)
print(arr2)

In [ ]:
arr3 = np.ones([4,5],dtype=int)
print(arr3)

In [49]:
arr4 = np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr6 = np.arange(1,100)
print(arr6)

In [ ]:
arr7 = np.arange(100,0,-1)
print(arr7)

In [58]:
even_arr1 = np.arange(0,50,2)
print(even_arr1)
odd = np.arange(1,50,2)
print(odd)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [60]:
array11 = np.eye(4,dtype=int)
print(array11)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [61]:
a12 = np.random.rand(4)
print(a12)

[0.65944386 0.29132756 0.64121352 0.56870233]


In [79]:
a13 = np.random.rand(3,4)
print(a13)

[[0.26483899 0.3991167  0.16680838 0.33172831]
 [0.18209817 0.315813   0.72275144 0.80138006]
 [0.78437994 0.98343494 0.73255254 0.67404602]]


In [77]:
a13 = np.random.randn(3,4)
print(a13)

[[ 0.51437563  1.28635511 -0.66894023  0.08945994]
 [ 1.15563384  0.48752171 -0.17880084 -1.13570357]
 [ 1.0818692   0.61363965  0.43863898 -1.19518699]]


In [89]:
a14 = np.random.randint(20,30)
print(a14)

22


In [90]:
array13 = np.random.randint(10,20,size = 4)
print(array13)

[12 15 16 10]


In [91]:
array13 = np.random.randint(10,20,size = (2,3))
print(array13)

[[11 10 18]
 [16 15 14]]


In [95]:
a15 = np.array([4,3,7,4,9,15,35])
print(a15)
print(np.sort(a15))


[ 4  3  7  4  9 15 35]
[ 3  4  4  7  9 15 35]


In [100]:
print(a15)
print(np.square(a15))
print(np.sqrt(a15))

[ 4  3  7  4  9 15 35]
[  16    9   49   16   81  225 1225]
[2.         1.73205081 2.64575131 2.         3.         3.87298335
 5.91607978]


In [102]:
print(np.std(a15))
print(np.var(a15))

10.515294982615968
110.57142857142857


In [103]:
arr14 = np.array([[1,2,3],[4,5,6]])
print(arr14)

[[1 2 3]
 [4 5 6]]


In [104]:
np.shape(arr14)

(2, 3)

In [111]:
arr14.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
arr14.size()

TypeError: 'int' object is not callable